// Generated by https://github.com/zhyupe/ffxiv-opcode-worker
using System.Collections.Generic;

namespace FFXIVConstants
{
    public static class CN
    {
        public const string Version = "7.41";

        public static Dictionary<string, object> Constants = new Dictionary<string, object>
        {
            { "InventoryOperationBaseValue", 0x023a },
        };
    }
}
