// Generated by https://github.com/zhyupe/ffxiv-opcode-worker

namespace FFXIVOpcodes.CN
{
    public enum ServerLobbyIpcType : ushort
    {

    };

    public enum ClientLobbyIpcType : ushort
    {

    };

    public enum ServerZoneIpcType : ushort
    {
        ActorCast = 0x0246,
        ActorControl = 0x02E1,
        ActorControlSelf = 0x01D2,
        ActorControlTarget = 0x03B3,
        ActorGauge = 0x00F4,
        ActorMove = 0x012F,
        ActorSetPos = 0x015F,
        AirshipExplorationResult = 0x0139,
        AirshipStatus = 0x0187,
        AirshipStatusList = 0x033F,
        AirshipTimers = 0x01A3,
        AoeEffect16 = 0x0108,
        AoeEffect24 = 0x0132,
        AoeEffect32 = 0x02A6,
        AoeEffect8 = 0x0213,
        BattleTalk2 = 0x026b,
        BossStatusEffectList = 0x02F9,
        CEDirector = 0x026D,
        CFNotify = 0x0217,
        CFPreferredRole = 0x0371,
        ContainerInfo = 0x02DA,
        CountdownCancel = 0x00EC,
        CountdownInitiate = 0x0388,
        CurrencyCrystalInfo = 0x0097,
        DesynthResult = 0x028c,
        Effect = 0x012E,
        EffectResult = 0x0189,
        EnvironmentControl = 0x021E,
        EventFinish = 0x027B,
        EventPlay = 0x01fb,
        EventPlay32 = 0x037f,
        EventPlay4 = 0x03aa,
        EventStart = 0x0072,
        Examine = 0x02FD,
        ExamineSearchInfo = 0x0395,
        FateInfo = 0x00AB,
        FreeCompanyDialog = 0x02E2,
        FreeCompanyInfo = 0x0301,
        HousingWardInfo = 0x02DD,
        InitZone = 0x0148,
        InventoryActionAck = 0x02E6,
        InventoryTransaction = 0x02A7,
        InventoryTransactionFinish = 0x00E3,
        IslandWorkshopSupplyDemand = 0x0254,
        ItemInfo = 0x0279,
        ItemMarketBoardInfo = 0x0366,
        Logout = 0x0364,
        MapEffect12 = 0x010D,
        MapEffect4 = 0x020A,
        MapEffect8 = 0x00CA,
        MarketBoardItemListing = 0x0128,
        MarketBoardItemListingCount = 0x0248,
        MarketBoardItemListingHistory = 0x0190,
        MarketBoardPurchase = 0x0272,
        MarketBoardSearchResult = 0x00D0,
        MiniCactpotInit = 0x02bc,
        NpcSpawn = 0x00D8,
        NpcSpawn2 = 0x0100,
        NpcYell = 0x03D1,
        ObjectSpawn = 0x0309,
        PlaceFieldMarker = 0x01B9,
        PlaceFieldMarkerPreset = 0x026A,
        PlayerSetup = 0x0299,
        PlayerSpawn = 0x0107,
        PlayerStats = 0x0265,
        Playtime = 0x01E9,
        PrepareZoning = 0x0376,
        RetainerInformation = 0x031C,
        RSV = 0x0224,
        StatusEffectList = 0x0197,
        StatusEffectList2 = 0x03E6,
        StatusEffectList3 = 0x00BE,
        SubmarineExplorationResult = 0x0229,
        SubmarineProgressionStatus = 0x02E5,
        SubmarineStatusList = 0x00CE,
        SubmarineTimers = 0x02FB,
        SystemLogMessage = 0x0365,
        UpdateClassInfo = 0x030e,
        UpdateHpMpTp = 0x0222,
        UpdateInventorySlot = 0x02ED,
        UpdateSearchInfo = 0x0256,
        WeatherChange = 0x02ab,
        WorldVisitQueue = 0x039a,
    };

    public enum ClientZoneIpcType : ushort
    {
        ChatHandler = 0x0304,
        ClientTrigger = 0x0301,
        InventoryModifyHandler = 0x0092,
        MarketBoardPurchaseHandler = 0x039A,
        MarketBoardRequestItemListingInfo = 0x010a,
        SetSearchInfoHandler = 0x00A1,
        UpdatePositionHandler = 0x00A2,
        UpdatePositionInstance = 0x0065,
    };

    public enum ServerChatIpcType : ushort
    {

    };

    public enum ClientChatIpcType : ushort
    {

    };
}
