// Generated by https://github.com/zhyupe/ffxiv-opcode-worker

namespace FFXIVOpcodes.CN
{
    enum ServerLobbyIpcType : ushort
    {

    };

    enum ClientLobbyIpcType : ushort
    {

    };

    enum ServerZoneIpcType : ushort
    {
        ActorCast = 0x013A,
        ActorControl = 0x012E,
        ActorControlSelf = 0x0303,
        ActorControlTarget = 0x01D2,
        ActorGauge = 0x03C0,
        ActorMove = 0x0195,
        ActorSetPos = 0x03C6,
        AirshipExplorationResult = 0x00D8,
        AirshipStatus = 0x01E8,
        AirshipStatusList = 0x010E,
        AoeEffect16 = 0x02D5,
        AoeEffect24 = 0x00E1,
        AoeEffect32 = 0x00C7,
        AoeEffect8 = 0x01E5,
        CEDirector = 0x024E,
        CFNotify = 0x00C3,
        CFPreferredRole = 0x027A,
        ContainerInfo = 0x02F9,
        CurrencyCrystalInfo = 0x0093,
        DesynthResult = 0x031C,
        Effect = 0x03B1,
        EffectResult = 0x018D,
        EventFinish = 0x025B,
        EventPlay = 0x03A0,
        EventPlay4 = 0x0233,
        EventStart = 0x008B,
        Examine = 0x0219,
        ExamineSearchInfo = 0x01ED,
        FreeCompanyDialog = 0x0213,
        FreeCompanyInfo = 0x03C9,
        HousingWardInfo = 0x01AA,
        InitZone = 0x0367,
        InventoryActionAck = 0x01E1,
        InventoryTransaction = 0x0182,
        InventoryTransactionFinish = 0x0220,
        ItemInfo = 0x0305,
        ItemMarketBoardInfo = 0x03E0,
        MarketBoardItemListing = 0x01A2,
        MarketBoardItemListingCount = 0x006C,
        MarketBoardItemListingHistory = 0x02FC,
        MarketBoardPurchase = 0x022C,
        MarketBoardSearchResult = 0x03E5,
        MiniCactpotInit = 0x00C0,
        NpcSpawn = 0x00AA,
        ObjectSpawn = 0x0306,
        PlaceFieldMarker = 0x02DC,
        PlaceFieldMarkerPreset = 0x0104,
        PlayerSetup = 0x00EA,
        PlayerSpawn = 0x00F1,
        PlayerStats = 0x0142,
        Playtime = 0x0351,
        PrepareZoning = 0x0345,
        ResultDialog = 0x0237,
        RetainerInformation = 0x0323,
        SomeDirectorUnk4 = 0x030B,
        StatusEffectList = 0x0126,
        StatusEffectList2 = 0x0160,
        SubmarineExplorationResult = 0x02B9,
        SubmarineProgressionStatus = 0x033A,
        SubmarineStatusList = 0x00AF,
        UpdateClassInfo = 0x03AB,
        UpdateHpMpTp = 0x03C8,
        UpdateInventorySlot = 0x0183,
        UpdateSearchInfo = 0x01D8,
    };

    enum ClientZoneIpcType : ushort
    {
        ChatHandler = 0x0374,
        ClientTrigger = 0x007C,
        InventoryModifyHandler = 0x0281,
        MarketBoardPurchaseHandler = 0x0111,
        SetSearchInfoHandler = 0x00F5,
        UpdatePositionHandler = 0x009A,
        UpdatePositionInstance = 0x030A,
    };

    enum ServerChatIpcType : ushort
    {

    };

    enum ClientChatIpcType : ushort
    {

    };
}
